export default {
    "componentName": "GlBlockComponentInvoke",
    "displayMode": "Tile",
    "iconType": "gl-api",
    "group": "block_page",
    "title": "调用组件方法",
    "useBy": ["freePage"],
    "blockContent": "调用组件的方法,组件为:${componentId}，方法名为:${methodName}",
    "properties": [{
        "name": "appId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "应用ID",
        "setterComponentName": "AInput",
        "placeholder": "不填写表示当前应用"
    }, {
        "name": "extendId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面",
        "setterComponentName": "GlPageSelect",
        "enableValueExpress": false
    }, {
        "name": "componentId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "调用的组件",
        "setterComponentName": "GlPageComponentSelect",
        "enableValueExpress": false
    }, {
        "name": "methodName",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "调用组件方法",
        "setterComponentName": "GlComponentMethodSelect",
        "enableValueExpress": false
    }, {
        "name": "params",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "方法参数",
        "_showSub": true,
        "properties": [{
            "name": "pName",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "参数名",
            "setterComponentName": "AInput"
        }, {
            "name": "pValue",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "参数值",
            "setterComponentName": "AInput"
        }, {
            "name": "pType",
            "setterComponentProps": {
                "allowClear": true,
                "options": [{"label": "字符串", "value": "string"}, {
                    "label": "布尔",
                    "value": "boolean"
                }, {"label": "表达式", "value": "express"}, {"label": "数值", "value": "number"}, {
                    "label": "数组",
                    "value": "array"
                }, {"label": "对象", "value": "object"}]
            },
            "setterComponentVModelName": "modelValue",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "title": "类型",
            "setterComponentName": "ASelect"
        }],
        "setterComponentName": "GlObjectArraySetter",
        "titleField": "pName"
    }],
    "actions": []
}