export default {
    "componentName": "GlBlockOpenComponentPage",
    "displayMode": "Tile",
    "iconType": "gl-file",
    "group": "block_page",
    "title": "打开组件页面",
    "useBy": ["freePage"],
    "blockContent": "打开组件页面，应用Id为：${appId},页面为:${title}",
    "properties": [{
        "name": "appId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "应用ID",
        "setterComponentName": "AInput",
        "placeholder": "不填写表示当前应用",
        "enableValueExpress": false
    }, {
        "name": "extendId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "打开的页面",
        "setterComponentName": "GlPageSelect"
    }, {
        "name": "mode",
        "title": "页面模式",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentName": "ASelect",
        "setterComponentProps": {
            "options": [
                {
                    "label": "抽屉",
                    "value": "Drawer"
                },
                {
                    "label": "弹层",
                    "value": "Modal"
                }
            ]
        }
    }, {
        "name": "title",
        "setterComponentProps": {"value": "默认为1024px"},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面标题",
        "setterComponentName": "AInput",
        "enableValueExpress": true
    }, {
        "name": "width",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面宽度",
        "setterComponentName": "AInput",
        "enableValueExpress": true
    }, {
        "name": "params",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面参数",
        "_showSub": false,
        "properties": [{
            "name": "name",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "参数名",
            "setterComponentName": "AInput"
        }, {
            "name": "valueExpression",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "setterComponentProps": {"showInput": true},
            "setterComponentVModelName": "modelValue",
            "setterComponentName": "GlExpressionSetter",
            "title": "参数值",
        }],
        "setterComponentName": "GlObjectArraySetter",
        "titleField": "name",
        "enableValueExpress": false
    }, {
        "name": "okText",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "确认按钮文字",
        "setterComponentName": "AInput",
        "enableValueExpress": true
    }, {
        "name": "cancelText",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "取消按钮文字",
        "setterComponentName": "AInput",
        "enableValueExpress": true
    }, {
        "name": "hideCancel",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "隐藏取消按钮",
        "setterComponentName": "ASwitch",
        "enableValueExpress": false
    }, {
        "name": "invokeBlocks",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {
            "options": [{
                "label": "确认操作时触发，如可做表单保存工作",
                "value": "onBeforeOk",
            }, {
                "label": "页面关闭后（动画结束）触发",
                "value": "onClose",
            }, {"label": "页面打开后（动画结束）触发", "value": "onOpen", "__YJe434P13sWjPAcCS1": "onOpen"}],
            "multiple": true,
            "allowClear": false
        },
        "setterComponentVModelName": "modelValue",
        "title": "调用指令",
        "setterComponentName": "ASelect"
    }]
}