export default {
    "componentName": "GlBlockConfirm",
    "displayMode": "Tile",
    "iconType": "gl-file",
    "group": "block_page",
    "title": "弹出确认",
    "useBy": ["freePage"],
    "blockContent": "弹出确认框，标题为:${title}，内容为:${content}",
    "properties": [{
        "name": "title",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "标题",
        "setterComponentName": "AInput",
        "placeholder": ""
    }, {
        "name": "content",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "内容",
        "setterComponentName": "AInput"
    }, {
        "name": "varName",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "变量名",
        "placeholder": "结果回写变量名称",
        "description": "点确认或取消时，值回写的变量，若点确认，值为true，则点取消或关闭，值为false",
        "setterComponentName": "AInput"
    }],
    "actions": []
}