export default {
    "componentName": "GlBlockSetVisible",
    "displayMode": "Tile",
    "iconType": "gl-hide",
    "group": "block_page",
    "title": "设置组件可见",
    "useBy": ["freePage"],
    "blockContent": "设置组件:${componentId}，是否为不渲染（不可见）:${unRender}",
    "properties": [{
        "name": "appId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "应用ID",
        "setterComponentName": "AInput",
        "placeholder": "不填写表示当前应用"
    }, {
        "name": "extendId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面",
        "setterComponentName": "GlPageSelect",
        "enableValueExpress": false
    }, {
        "name": "componentId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "调用的组件",
        "setterComponentName": "GlPageComponentSelect",
        "enableValueExpress": false
    },{
        "name": "unRender",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "不渲染",
        "setterComponentName": "ASwitch"
    }],
    "actions": []
}