export default {
    "componentName": "GlBlockOpenComponentPage",
    "displayMode": "Tile",
    "iconType": "gl-file",
    "group": "block_page",
    "title": "打开组件页面",
    "useBy": ["freePage"],
    "blockContent": "打开组件页面，应用Id为：${appId},页面为:${title}",
    "properties": [{
        "name": "appId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "应用ID",
        "setterComponentName": "AInput",
        "placeholder": "不填写表示当前应用",
        "enableValueExpress": false
    }, {
        "name": "extendId",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "打开的页面",
        "setterComponentName": "GlPageSelect"
    }, {
        "name": "title",
        "setterComponentProps": {"value": "默认为1024px"},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面标题",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "width",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面宽度",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "params",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "页面参数",
        "_showSub": false,
        "properties": [{
            "name": "pName",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "参数名",
            "setterComponentName": "AInput"
        }, {
            "name": "pValue",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "参数值",
            "setterComponentName": "AInput"
        }, {
            "name": "pType",
            "setterComponentProps": {
                "allowClear": true,
                "options": [{"label": "字符串", "value": "string"}, {
                    "label": "布尔",
                    "value": "boolean"
                }, {"label": "表达式", "value": "express"}, {"label": "数值", "value": "number"}, {
                    "label": "数组",
                    "value": "array"
                }, {"label": "对象", "value": "object"}]
            },
            "setterComponentVModelName": "modelValue",
            "group": "base",
            "type": "props",
            "show": true,
            "expanded": true,
            "title": "类型",
            "setterComponentName": "ASelect"
        }],
        "setterComponentName": "GlObjectArraySetter",
        "titleField": "pName",
        "enableValueExpress": false
    }, {
        "name": "okText",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "确认按钮文字",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "cancelText",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "取消按钮文字",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "hideCancel",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "隐藏取消按钮",
        "setterComponentName": "ASwitch",
        "enableValueExpress": false
    }, {
        "name": "invokeBlocks",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {
            "options": [{
                "label": "确认操作前触发，如可做些表单验证等工作",
                "value": "onBeforeOk",
                "__YJe434P13sWjPAcCS1": "onBeforeOk"
            }, {
                "label": "页面关闭后（动画结束）触发",
                "value": "onClose",
                "__YJe434P13sWjPAcCS1": "onClose"
            }, {"label": "页面打开后（动画结束）触发", "value": "onOpen", "__YJe434P13sWjPAcCS1": "onOpen"}],
            "multiple": true,
            "allowClear": false
        },
        "setterComponentVModelName": "modelValue",
        "title": "开启指令调用",
        "setterComponentName": "ASelect"
    }],
    "actions": []
}