export default [
    {componentName: 'AButton', title: '按钮'},
    {componentName: 'AInput', title: '单行输入'},
    {componentName: 'ATextarea', title: '多行输入'},
    {componentName: 'AInputNumber', title: '数字输入'},
    {componentName: 'ASwitch', title: '开关'},
    {componentName: 'ASelect', title: '下拉选择'},
    {componentName: 'GlDict', title: '数据字典'},
    {componentName: 'GlDynamicSelect', title: '实体选择器'},
    {componentName: 'ADatePicker', title: '日期选择器'},
    {componentName: 'ATimePicker', title: '时间选择器'},
    {componentName: 'GlUserSelect', title: '人员选择器'},
    {componentName: 'AUpload', title: '文件上传'},
    {componentName: 'GlText', title: '文本展示'},
    {componentName: 'GlImage', title: '图片展示'},
]