export default {
    "componentName": "GlDynamicSelect",
    "displayMode": "tile",
    "iconType": "gl-select",
    "group": "dataEntry",
    "title": "实体选择器",
    "alias": "select",
    "useBy": ["freePage"],
    "properties": [{
        "name": "label",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "标题",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "bindField",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "绑定字段",
        "setterComponentName": "GlEntityFieldSelect",
        "enableValueExpress": false
    }, {
        "name": "entityName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "选项源实体",
        "setterComponentName": "GlEntitySelect"
    }, {
        "name": "triggerMode",
        "setterComponentProps": {
            "options": [{
                "label": "组件创建时",
                "__wY748nFdYBExuM4FRD": "onCreated",
                "value": "onCreated"
            }, {"label": "被调用时", "__wY748nFdYBExuM4FRD": "onInvoked", "value": "onInvoked"}]
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "title": "触发模式",
        "setterComponentName": "ARadioGroup",
        "description": "不选择时，默认为组件创建时"
    }, {
        "name": "labelFieldName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "description": "在下拉列表中显示的实体字段名",
        "placeholder": "在下拉列表中显示的实体字段名",
        "title": "显示字段",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "valueFiledName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "值字段",
        "description": "实体中，用于作为值的字段名",
        "placeholder": "实体值字段名",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "valueFilter",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "title": "数据过滤",
        "_showSub": false,
        "properties": [{
            "name": "fieldName",
            "group": "base",
            "type": "props",
            "enableValueExpress": false,
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "setterComponentName": "GlFieldSelect",
            "title": "字段名"
        }, {
            "name": "cop",
            "group": "base",
            "type": "props",
            "enableValueExpress": false,
            "show": true,
            "expanded": true,
            "setterComponentProps": {
                "options": [{
                    "label": "等于",
                    "value": "eq",
                    "__sfh6bOn4TZO1ya3MA3": "eq"
                }, {"label": "不等于", "value": "neq", "__sfh6bOn4TZO1ya3MA3": "neq"}, {
                    "label": "小于",
                    "value": "lt",
                    "__sfh6bOn4TZO1ya3MA3": "lt"
                }, {"label": "小于等于", "value": "lte", "__sfh6bOn4TZO1ya3MA3": "lte"}, {
                    "label": "大于",
                    "value": "gt",
                    "__sfh6bOn4TZO1ya3MA3": "gt"
                }, {"label": "大于等于", "value": "gte", "__sfh6bOn4TZO1ya3MA3": "gte"}, {
                    "label": "开头包括",
                    "value": "sw",
                    "__sfh6bOn4TZO1ya3MA3": "sw"
                }, {"label": "结尾包括", "value": "ew", "__sfh6bOn4TZO1ya3MA3": "ew"}, {
                    "label": "包括",
                    "value": "contains",
                    "__sfh6bOn4TZO1ya3MA3": "contains"
                }]
            },
            "setterComponentVModelName": "modelValue",
            "title": "比较",
            "setterComponentName": "ASelect"
        }, {
            "name": "value",
            "group": "base",
            "type": "props",
            "enableValueExpress": true,
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "字段值",
            "setterComponentName": "AInput",
            "placeholder": ""
        }],
        "setterComponentName": "GlObjectArraySetter",
        "titleField": "fieldName",
        "subTitleField": "",
        "alarmIfNoSubTitle": ""
    }, {
        "name": "extraFieldAndBindIds",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "title": "数据联动",
        "description": "获取更多的字段信息，并设置到指定的组件中",
        "_showSub": false,
        "properties": [{
            "name": "fieldName",
            "group": "base",
            "type": "props",
            "enableValueExpress": false,
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "字段名",
            "placeholder": "",
            "setterComponentName": "GlFieldSelect"
        }, {
            "name": "bindId",
            "group": "base",
            "type": "props",
            "enableValueExpress": false,
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "setterComponentName": "AInput",
            "title": "绑定组件"
        }],
        "setterComponentName": "GlObjectArraySetter",
        "titleField": "fieldName",
        "alarmIfNoSubTitle": "未设置",
        "subTitleField": ""
    }, {
        "name": "size",
        "setterComponentProps": {
            "mode": "SECRET_COMBOBOX_MODE_DO_NOT_USE",
            "optionType": "button",
            "options": [{"label": "大", "value": "large", "__TjjKdG3HMXO3v7kSND": "large"}, {
                "label": "默认",
                "value": "default",
                "__TjjKdG3HMXO3v7kSND": "default"
            }, {"label": "小", "value": "small", "__TjjKdG3HMXO3v7kSND": "small"}],
            "defaultValue": "default"
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "大小",
        "setterComponentName": "ARadioGroup",
        "show": true,
        "expanded": true,
        "enableValueExpress": false
    }, {
        "name": "allowSearch",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "允许搜索",
        "setterComponentName": "ASwitch",
        "enableValueExpress": false
    }, {
        "name": "allowClear",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "点击清除",
        "setterComponentName": "ASwitch",
        "show": true,
        "expanded": true,
        "enableValueExpress": false
    }],
    "actions": [{"name": "onValueChange", "description": "", "title": "值改变"}],
    "displayOnStage": "inline-block",
    "methods": [{"name": "fetchData", "title": "获取数据"}]
}