export default {
    "componentName": "GlDynamicSelect",
    "displayMode": "tile",
    "iconType": "gl-select",
    "group": "dataEntry",
    "title": "实体选择器",
    "alias": "select",
    "useBy": ["freePage"],
    "properties": [{
        "name": "label",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "标题",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "bindField",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "绑定字段",
        "setterComponentName": "GlEntityFieldSelect",
        "enableValueExpress": false
    }, {
        "name": "entityName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "选项源实体",
        "setterComponentName": "GlEntitySelect"
    }, {
        "name": "labelFieldName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "description": "在下拉列表中显示的实体字段名",
        "placeholder": "在下拉列表中显示的实体字段名",
        "title": "显示字段",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "valueFiledName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "值字段",
        "description": "实体中，用于作为值的字段名",
        "placeholder": "实体值字段名",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "extraFieldAndBindIds",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "title": "数据联动",
        "description": "获取更多的字段信息，并设置到指定的组件中",
        "_showSub": true,
        "properties": [{
            "name": "fieldName",
            "group": "base",
            "type": "props",
            "enableValueExpress": false,
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "title": "字段名",
            "placeholder": "",
            "setterComponentName": "GlFieldSelect"
        }, {
            "name": "bindId",
            "group": "base",
            "type": "props",
            "enableValueExpress": false,
            "show": true,
            "expanded": true,
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "setterComponentName": "AInput",
            "title": "绑定组件"
        }],
        "setterComponentName": "GlObjectArraySetter",
        "titleField": "fieldName",
        "alarmIfNoSubTitle": true
    }, {
        "name": "size",
        "setterComponentProps": {
            "mode": "SECRET_COMBOBOX_MODE_DO_NOT_USE",
            "optionType": "button",
            "options": [{"label": "大", "value": "large", "__TjjKdG3HMXO3v7kSND": "large"}, {
                "label": "默认",
                "value": "default",
                "__TjjKdG3HMXO3v7kSND": "default"
            }, {"label": "小", "value": "small", "__TjjKdG3HMXO3v7kSND": "small"}],
            "defaultValue": "default"
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "大小",
        "setterComponentName": "ARadioGroup",
        "show": true,
        "expanded": true,
        "enableValueExpress": false
    }, {
        "name": "allowSearch",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "允许搜索",
        "setterComponentName": "ASwitch",
        "enableValueExpress": false
    }, {
        "name": "allowClear",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "点击清除",
        "setterComponentName": "ASwitch",
        "show": true,
        "expanded": true,
        "enableValueExpress": false
    }],
    "actions": [{"name": "onValueChange", "description": "", "title": "值改变"}, {
        "name": "onMounted",
        "description": "组件加载完时触发，和Vue的onMounted一致",
        "title": "加载完"
    }, {"name": "onUpdated", "description": "组件更新时触发，和Vue的onUpdated一致", "title": "加载完"}],
    "displayOnStage": "inline-block"
}