export default {
    "componentName": "GlDynamicSelect",
    "displayMode": "tile",
    "iconType": "gl-select",
    "group": "dataEntry",
    "title": "实体选择器",
    "alias": "select",
    "useBy": ["freePage"],
    "properties": [{
        "name": "label",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "标题",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "bindField",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "绑定字段",
        "setterComponentName": "GlEntityFieldSelect",
        "enableValueExpress": false
    }, {
        "name": "entityName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "选项源实体",
        "setterComponentName": "GlEntitySelect"
    }, {
        "name": "labelFieldName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "description": "在下拉列表中显示的实体字段名",
        "placeholder": "在下拉列表中显示的实体字段名",
        "title": "显示字段",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "valueFiledName",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "值字段",
        "description": "实体中，用于作为值的字段名",
        "placeholder": "实体值字段名",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "size",
        "setterComponentProps": {
            "mode": "SECRET_COMBOBOX_MODE_DO_NOT_USE",
            "optionType": "button",
            "options": [{"label": "大", "value": "large", "__TjjKdG3HMXO3v7kSND": "large"}, {
                "label": "默认",
                "value": "default",
                "__TjjKdG3HMXO3v7kSND": "default"
            }, {"label": "小", "value": "small", "__TjjKdG3HMXO3v7kSND": "small"}],
            "defaultValue": "default"
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "大小",
        "setterComponentName": "ARadioGroup",
        "show": true,
        "expanded": true,
        "enableValueExpress": false
    }, {
        "name": "allowSearch",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "允许搜索",
        "setterComponentName": "ASwitch",
        "enableValueExpress": false
    }, {
        "name": "allowClear",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "点击清除",
        "setterComponentName": "ASwitch",
        "show": true,
        "expanded": true,
        "enableValueExpress": false
    },  {
        "name": "placeholder",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "提示文字",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }],
    "actions": [{"name": "onValueChange", "description": "", "title": "值改变"}],
    "displayOnStage": "inline-block"
}