export default {
    "componentName": "AAutoComplete",
    "displayMode": "Tile",
    "iconType":"gl-autoComplete",
    "group": "dataEntry",
    "title": "自动完成",
    "useBy": ["freePage"],
    "properties": [{
        "name": "allowClear",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "支持清除, 单选模式有效",
        "title": "清除",
        "setterComponentName": "ASwitch"
    }, {
        "name": "autofocus",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "自动获取焦点",
        "setterComponentName": "ASwitch",
        "title": "自动焦点"
    }, {
        "name": "backfill",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "使用键盘选择选项的时候把选中项回填到输入框中",
        "setterComponentName": "ASwitch",
        "title": "键盘选择回填"
    }, {
        "name": "defaultActiveFirstOption",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "是否默认高亮第一个选项。",
        "title": "高亮第一项",
        "setterComponentName": "ASwitch"
    }, {
        "name": "defaultOpen",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "是否默认展开下拉菜单",
        "title": "默认展开下拉",
        "setterComponentName": "ASwitch"
    }, {
        "name": "disabled",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "是否禁用",
        "title": "禁用",
        "setterComponentName": "ASwitch"
    }, {
        "name": "dropdownMatchSelectWidth",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "下拉菜单和选择器同宽。默认将设置 min-width，当值小于选择框宽度时会被忽略。false 时会关闭虚拟滚动",
        "title": "同宽",
        "setterComponentName": "ASwitch"
    }, {
        "name": "options",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "_showSub": false,
        "properties": [{
            "name": "text",
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "group": "base",
            "type": "props",
            "setterComponentName": "AInput",
            "title": "标题"
        }, {
            "name": "value",
            "setterComponentProps": {},
            "setterComponentVModelName": "modelValue",
            "group": "base",
            "type": "props",
            "setterComponentName": "AInput",
            "title": "值"
        }],
        "setterComponentName": "GlObjectArraySetter",
        "description": "自动完成的数据源",
        "title": "数据源"
    }],
    "diplayMode": "Tile"
}