export default {
    "componentName": "GlText",
    "displayMode": "Tile",
    "iconType": "gl-text",
    "group": "dataDisplay",
    "title": "文本",
    "alias": "text",
    "useBy": ["freePage"],
    "properties": [{
        "name": "bold",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "粗体",
        "setterComponentName": "ASwitch",
        "enableValueExpress": true
    }, {
        "name": "mark",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "标记样式",
        "setterComponentName": "ASwitch"
    }, {
        "name": "underline",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "下划线",
        "setterComponentName": "ASwitch"
    }, {
        "name": "delete",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "删除线",
        "setterComponentName": "ASwitch"
    }, {
        "name": "code",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "代码块",
        "setterComponentName": "ASwitch"
    }, {
        "name": "editable",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "可编辑",
        "setterComponentName": "ASwitch"
    }, {
        "name": "copyable",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "可复制",
        "setterComponentName": "ASwitch"
    }, {
        "name": "disabled",
        "group": "base",
        "type": "props",
        "enableValueExpress": true,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "禁用",
        "setterComponentName": "ASwitch"
    }],
    "actions": [{"name": "change", "description": "", "title": "值改变"}]
}