export default {
    "componentName": "AInputNumber",
    "displayMode": "Tile",
    "iconType": "gl-inputNumber",
    "group": "dataEntry",
    "title": "数字输入",
    "useBy": ["freePage"],
    "properties": [{
        "name": "addonAfter",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "带标签的 input，设置后置标签",
        "title": "后置标签",
        "setterComponentName": "AInput"
    }, {
        "name": "addonBefore",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "前置标签",
        "description": "带标签的 input，设置前置标签",
        "setterComponentName": "AInput"
    }, {
        "name": "autofocus",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "自动获取焦点",
        "title": "自动焦点",
        "setterComponentName": "ASwitch"
    }, {
        "name": "bordered",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "title": "边框",
        "setterComponentName": "ASwitch"
    }, {
        "name": "controls",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "title": "增减按钮",
        "setterComponentName": "ASwitch"
    }, {
        "name": "decimalSeparator",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "小数点",
        "setterComponentName": "AInput"
    }, {
        "name": "defaultValue",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "初始值",
        "setterComponentName": "AInputNumber"
    }, {
        "name": "disabled",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "title": "禁用",
        "setterComponentName": "ASwitch"
    }, {
        "name": "formatter",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "指定输入框展示值的格式function(value: number | string, info: { userTyping: boolean, input: string }): string",
        "title": "值的格式",
        "setterComponentName": "AInput"
    }, {
        "name": "keyboard",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "是否启用键盘快捷行为",
        "title": "快捷键盘",
        "setterComponentName": "ASwitch"
    }, {
        "name": "max",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "最大值",
        "setterComponentName": "AInputNumber"
    }, {
        "name": "min",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "最小值",
        "setterComponentName": "AInputNumber"
    }, {
        "name": "parser",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "description": "指定从 formatter 里转换回数字的方式，和 formatter 搭配使用,function( string): number",
        "title": "转换方式"
    }, {
        "name": "precision",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "数值精度",
        "setterComponentName": "AInputNumber"
    }, {
        "name": "prefix",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "带有前缀图标的 input",
        "title": "前缀图标",
        "setterComponentName": "AInput"
    }, {
        "name": "size",
        "setterComponentProps": {
            "optionType": "button",
            "buttonStyle": "solid",
            "options": [{"label": "large", "value": "large"}, {
                "label": "default",
                "value": "default"
            }, {"label": "small", "value": "small"}]
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "大小",
        "setterComponentName": "ARadioGroup"
    }, {
        "name": "step",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "每次改变步数，可以为小数",
        "title": "步数",
        "setterComponentName": "AInputNumber"
    }, {
        "name": "stringMode",
        "setterComponentProps": {},
        "setterComponentVModelName": "checked",
        "group": "base",
        "type": "props",
        "description": "字符值模式，开启后支持高精度小数。同时 change 事件将返回 string 类",
        "title": "字符值模式",
        "setterComponentName": "ASwitch"
    }],
    "diplayMode": "Tile"
}
