export default {
    "componentName": "AInput",
    "displayMode": "Tile",
    "iconType": "gl-input",
    "group": "dataEntry",
    "title": "字符输入",
    "useBy": ["freePage"],
    "properties": [{
        "name": "size",
        "setterComponentProps": {
            "mode": "SECRET_COMBOBOX_MODE_DO_NOT_USE",
            "optionType": "button",
            "options": [{"label": "大", "value": "large"}, {"label": "默认", "value": "default"}, {
                "label": "小",
                "value": "small"
            }],
            "defaultValue": "default"
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "控件大小",
        "setterComponentName": "ARadioGroup",
        "show": true,
        "expanded": true
    }, {
        "name": "prepend",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "slots",
        "show": true,
        "expanded": true,
        "title": "前置标签",
        "setterComponentName": "AInput",
        "slotComponentName": "GlText",
        "slotComponentBindTarget": "v-model"
    }, {
        "name": "append",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "slots",
        "show": true,
        "expanded": true,
        "title": "后置标签",
        "setterComponentName": "AInput",
        "slotComponentName": "GlText",
        "slotComponentBindTarget": "v-model"
    }, {
        "name": "allowClear",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "点击清除",
        "setterComponentName": "ASwitch",
        "show": true,
        "expanded": true
    }, {
        "name": "disabled",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "是否禁用状态，默认为 false",
        "title": "是否禁用",
        "setterComponentName": "ASwitch",
        "show": true,
        "expanded": true
    }, {
        "name": "readonly",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "只读",
        "setterComponentName": "ASwitch"
    }, {
        "name": "placeholder",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "提示文字",
        "setterComponentName": "AInput"
    }, {
        "name": "maxlength",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "最大长度",
        "setterComponentName": "AInputNumber",
        "show": true,
        "expanded": true
    }, {
        "name": "showWordLimit",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "显示字数",
        "setterComponentName": "ASwitch"
    }, {
        "name": "defaultValue",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "输入框默认内容",
        "title": "默认内容",
        "setterComponentName": "AInput",
        "show": true,
        "expanded": true
    }, {
        "name": "fieldName",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "绑定字段",
        "setterComponentName": "GlFieldSelect"
    }],
    "diplayMode": "Tile",
    "actions": []
}