export default {
    "componentName": "AInputNumber",
    "displayMode": "Tile",
    "iconType": "gl-inputNumber",
    "group": "dataEntry",
    "title": "数字输入",
    "useBy": ["freePage"],
    "properties": [{
        "name": "bindField",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "绑定字段",
        "setterComponentName": "GlFieldSelect"
    }, {
        "name": "defaultValue",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "默认值",
        "setterComponentName": "AInputNumber",
        "show": true,
        "expanded": true,
        "placeholder": "默认值（非受控模式）"
    }, {
        "name": "mode",
        "setterComponentProps": {
            "options": [{"label": "按钮内嵌", "value": "embed"}, {
                "label": "左右按钮",
                "value": "button"
            }]
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "模式",
        "description": "（embed：按钮内嵌模式，button：左右按钮模式）",
        "setterComponentName": "ARadioGroup"
    }, {
        "name": "precision",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "数值精度",
        "setterComponentName": "AInputNumber",
        "show": true,
        "expanded": true
    }, {
        "name": "step",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "description": "每次改变步数，可以为小数",
        "title": "步数",
        "setterComponentName": "AInputNumber",
        "show": true,
        "expanded": true
    }, {
        "name": "disabled",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "禁用",
        "setterComponentName": "ASwitch",
        "show": true,
        "expanded": true
    }, {
        "name": "error",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "错误状态",
        "placeholder": "是否为错误状态",
        "setterComponentName": "ASwitch"
    }, {
        "name": "max",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "最大值",
        "setterComponentName": "AInputNumber",
        "show": true,
        "expanded": true
    }, {
        "name": "min",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "最小值",
        "setterComponentName": "AInputNumber",
        "show": true,
        "expanded": true
    }, {
        "name": "placeholder",
        "setterComponentProps": {},
        "setterComponentVModelName": "",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "占位提示",
        "placeholder": "输入框提示文字"
    }, {
        "name": "size",
        "setterComponentProps": {
            "optionType": "button",
            "buttonStyle": "solid",
            "options": [{"label": "迷你", "value": "mini"}, {"label": "小", "value": "small"}, {
                "label": "中",
                "value": "medium"
            }, {"label": "大", "value": "large"}]
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "title": "大小",
        "setterComponentName": "ARadioGroup",
        "show": true,
        "expanded": true
    }, {
        "name": "allowClear",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "placeholder": "是否允许清空输入框",
        "title": "允许清空",
        "setterComponentName": "ASwitch"
    }, {
        "name": "readOnly",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "只读",
        "setterComponentName": "ASwitch"
    }, {
        "name": "append",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "slots",
        "show": true,
        "expanded": true,
        "title": "后置标签",
        "setterComponentName": "AInput",
        "slotComponentName":"GlText",
        "slotComponentBindTarget":"v-model"
    }, {
        "name": "prepend",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "slots",
        "show": true,
        "expanded": true,
        "title": "前置标签",
        "setterComponentName": "AInput",
        "slotComponentName":"GlText",
        "slotComponentBindTarget":"v-model"
    }],
    "diplayMode": "Tile"
}