export default {
    "componentName": "GlRefPage",
    "displayMode": "Tile",
    "iconType": "gl-file",
    "group": "layout",
    "title": "引用页面",
    "alias": "refPage",
    "useBy": ["freePage"],
    "properties": [{
        "name": "label",
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "show": true,
        "expanded": true,
        "title": "标题",
        "setterComponentName": "AInput",
        "enableValueExpress": false
    }, {
        "name": "pageType",
        "setterComponentProps": {
            "options": [{
                "label": "平台低代码配置页面",
                "value": "lowcode"
            }, {"label": "平台轻应用编码页面", "value": "code"}, {"label": "第三方页面", "value": "third"}]
        },
        "setterComponentVModelName": "modelValue",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "title": "页面类型",
        "description": "",
        "setterComponentName": "ARadioGroup",
        "setterDefaultValue": "lowcode"
    }, {
        "name": "pageSrc",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "页面地址",
        "description": "",
        "setterComponentName": "AInput",
        "placeholder": "https://www.xxx.com/xxx/xxx"
    }, {
        "name": "appId",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "title": "应用Id",
        "setterComponentName": "AInput",
        "placeholder": ""
    }, {
        "name": "extendId",
        "group": "base",
        "type": "props",
        "enableValueExpress": false,
        "show": true,
        "expanded": true,
        "setterComponentProps": {},
        "setterComponentVModelName": "modelValue",
        "setterComponentName": "GlPageSelect",
        "title": "配置页面"
    }]
}